/**
 * FulHash Types
 * Code generated by scripts/codegen/generate-fulhash-types.ts; DO NOT EDIT.
 */

/**
 * Supported hashing algorithms for FulHash
 */
export enum Algorithm {
  /**
   * XXH3 (128-bit)
   * Fast non-cryptographic hash (default). Excellent collision resistance, extremely high throughput (50GB/s+).
   */
  XXH3_128 = "xxh3-128",

  /**
   * SHA-256
   * Cryptographic security standard. Resistant to intentional collisions. Use for security verification.
   */
  SHA256 = "sha256",

  /**
   * CRC-32 (IEEE)
   * 32-bit Cyclic Redundancy Check. Standard for GZIP/ZIP/PNG legacy format interoperability.
   */
  CRC32 = "crc32",

  /**
   * CRC-32C (Castagnoli)
   * 32-bit CRC (Castagnoli). HW accelerated (SSE4.2/ARMv8). Use for cloud storage (GCS, AWS) and networking.
   */
  CRC32C = "crc32c",
}

/**
 * Standard digest payload returned by FulHash helpers
 */
export interface Digest {
  /**
   * Hash algorithm identifier
   */
  algorithm: "xxh3-128" | "crc32" | "crc32c" | "sha256";

  /**
   * Lowercase hexadecimal representation of the digest
   */
  hex: string;

  /**
   * Canonical string representation '<algorithm>:<hex>'
   */
  formatted: string;

  /**
   * Raw digest bytes (optional)
   */
  bytes?: number[];
}
