#!/usr/bin/env bun
/**
 * Embed SSOT assets into checked-in generated TS modules (v0.4.0).
 *
 * Walks tsfulmen's bundled Crucible asset trees and emits one ESM module per
 * domain under `src/assets/generated/`, each exporting an `EmbeddedAssetManifest`
 * ({ domain, files: { logicalPath -> raw text } }). These modules live in the
 * import graph, so a `bun --compile` single-file binary carries the assets with
 * no filesystem read. Generated modules are CHECKED IN (entarch decision); drift
 * vs. the on-disk trees is enforced by `make verify-embedded-assets`.
 *
 * Logical paths are package-root-relative POSIX (the AssetResolver namespace),
 * spanning both schemas/ and config/ so cross-tree `$ref` resolves through one
 * resolver.
 *
 * Usage:
 *   bunx tsx scripts/embed-assets.ts          # write generated modules
 *   bunx tsx scripts/embed-assets.ts --check   # fail if anything would change (drift)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import glob from "fast-glob";

interface DomainSpec {
  /** Domain label (also the generated filename stem). */
  name: string;
  /** Package-root-relative glob patterns for this domain's assets. */
  patterns: string[];
  /** Optional ignore globs. */
  ignore?: string[];
}

/**
 * Usage-oriented domain split (entarch §0.3). Keep each domain narrow so a
 * single-feature consumer doesn't pull the whole corpus.
 */
const DOMAINS: DomainSpec[] = [
  {
    name: "metaschema",
    patterns: ["schemas/crucible-ts/meta/**/*.json"],
    ignore: ["**/fixtures/**"],
  },
  {
    name: "schemas",
    patterns: [
      "schemas/crucible-ts/**/*.schema.json",
      "schemas/crucible-ts/**/*.schema.yaml",
      "schemas/crucible-ts/**/*.schema.yml",
    ],
  },
  {
    name: "foundry",
    patterns: [
      "config/crucible-ts/library/foundry/signals.yaml",
      "config/crucible-ts/library/foundry/patterns.yaml",
      "config/crucible-ts/library/foundry/http-statuses.yaml",
      "config/crucible-ts/library/foundry/mime-types.yaml",
      "config/crucible-ts/library/foundry/country-codes.yaml",
    ],
  },
  {
    name: "taxonomy",
    patterns: ["config/crucible-ts/taxonomy/metrics.yaml"],
  },
];

const ROOT = process.cwd();
const GEN_DIR = join(ROOT, "src", "assets", "generated");

function assertAtPackageRoot(): void {
  try {
    readFileSync(join(ROOT, "schemas", "crucible-ts", "meta", "draft-07", "schema.json"));
  } catch {
    console.error(
      "❌ embed-assets must run from the tsfulmen package root (schemas/crucible-ts not found).",
    );
    process.exit(1);
  }
}

async function collectDomain(spec: DomainSpec): Promise<Record<string, string>> {
  const matches = await glob(spec.patterns, {
    cwd: ROOT,
    absolute: false,
    onlyFiles: true,
    followSymbolicLinks: false,
    ignore: spec.ignore,
    dot: false,
  });
  const files: Record<string, string> = {};
  for (const logicalPath of matches.sort()) {
    files[logicalPath] = readFileSync(join(ROOT, logicalPath), "utf-8");
  }
  return files;
}

function renderModule(domain: string, files: Record<string, string>): string {
  const entries = Object.keys(files)
    .sort()
    .map(
      (logicalPath) => `    ${JSON.stringify(logicalPath)}: ${JSON.stringify(files[logicalPath])},`,
    )
    .join("\n");
  return `// AUTO-GENERATED by scripts/embed-assets.ts. DO NOT EDIT.
// Run \`make embed-assets\` to regenerate after \`make sync-ssot\`.
// Domain: ${domain} (${Object.keys(files).length} assets)
import type { EmbeddedAssetManifest } from "../types.js";

export const manifest: EmbeddedAssetManifest = {
  domain: ${JSON.stringify(domain)},
  files: {
${entries}
  },
};

export default manifest;
`;
}

function renderIndex(domains: string[]): string {
  const imports = domains
    .map((d) => `import { manifest as ${d}Manifest } from "./${d}.generated.js";`)
    .join("\n");
  const arrayEntries = domains.map((d) => `  ${d}Manifest,`).join("\n");
  const reexports = domains
    .map((d) => `export { manifest as ${d}Manifest } from "./${d}.generated.js";`)
    .join("\n");
  return `// AUTO-GENERATED by scripts/embed-assets.ts. DO NOT EDIT.
import { registerEmbeddedAssets } from "../embedded-resolver.js";
import type { EmbeddedAssetManifest } from "../types.js";
${imports}

${reexports}

/** All generated embedded-asset manifests, in deterministic domain order. */
export const embeddedManifests: readonly EmbeddedAssetManifest[] = [
${arrayEntries}
];

/**
 * Register every generated domain manifest with the embedded resolver. Call once
 * at startup (e.g. from a compiled-binary entrypoint) to make all SSOT assets
 * resolvable without the filesystem.
 */
export function registerAllEmbeddedAssets(): void {
  for (const manifest of embeddedManifests) {
    registerEmbeddedAssets(manifest);
  }
}
`;
}

function renderLoaders(domains: string[]): string {
  const entries = domains.map((d) => `  ${d}: () => import("./${d}.generated.js"),`).join("\n");
  return `// AUTO-GENERATED by scripts/embed-assets.ts. DO NOT EDIT.
// Lazy per-domain loaders. Importing this module does NOT pull any domain module
// (the values are dynamic-import thunks), so consumers/binaries load only the
// domains they touch. Cold dynamic import survives bun --compile (see
// scripts/verify-embedded-compile.ts).
import type { EmbeddedAssetManifest } from "../types.js";

export type DomainLoader = () => Promise<{ manifest: EmbeddedAssetManifest }>;

export const domainLoaders: Record<string, DomainLoader> = {
${entries}
};
`;
}

async function main(): Promise<void> {
  assertAtPackageRoot();
  const check = process.argv.includes("--check");

  const generated = new Map<string, string>();
  for (const spec of DOMAINS) {
    const files = await collectDomain(spec);
    if (Object.keys(files).length === 0) {
      console.error(`❌ Domain "${spec.name}" matched no files — check patterns.`);
      process.exit(1);
    }
    generated.set(join(GEN_DIR, `${spec.name}.generated.ts`), renderModule(spec.name, files));
  }
  generated.set(join(GEN_DIR, "index.ts"), renderIndex(DOMAINS.map((d) => d.name)));
  generated.set(join(GEN_DIR, "loaders.generated.ts"), renderLoaders(DOMAINS.map((d) => d.name)));

  let drift = false;
  for (const [path, content] of generated) {
    let current: string | null = null;
    try {
      current = readFileSync(path, "utf-8");
    } catch {
      current = null;
    }
    if (current === content) continue;
    drift = true;
    if (check) {
      console.error(`❌ Embedded asset drift: ${path.replace(`${ROOT}/`, "")} is stale.`);
    } else {
      writeFileSync(path, content);
      console.log(`✓ wrote ${path.replace(`${ROOT}/`, "")}`);
    }
  }

  if (check) {
    if (drift) {
      console.error("\n❌ Embedded assets are out of date. Run `make embed-assets`.");
      process.exit(1);
    }
    console.log("✅ Embedded assets are up to date.");
  } else {
    const total = DOMAINS.length;
    console.log(`✅ Embedded ${total} domains into src/assets/generated/`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
